# Generated by Django 3.2.9 on 2021-11-03 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id_person', models.AutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(blank=True, max_length=45, null=True)),
                ('person_last_name', models.CharField(max_length=45)),
                ('person_address', models.CharField(blank=True, max_length=45, null=True)),
                ('person_phone', models.CharField(blank=True, max_length=45, null=True)),
                ('person_dni', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PersonType',
            fields=[
                ('id_person_type', models.AutoField(primary_key=True, serialize=False)),
                ('person_type_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'person_type',
            },
        ),
        migrations.CreateModel(
            name='PriceProduct',
            fields=[
                ('id_price_product', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('shop_price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('start_date', models.DateField()),
                ('user_update', models.CharField(max_length=40)),
                ('date_update', models.DateField()),
            ],
            options={
                'db_table': 'price_product',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id_product', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id_product_type', models.AutoField(primary_key=True, serialize=False)),
                ('product_type_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product_type',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id_provider', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=45)),
                ('url', models.CharField(blank=True, max_length=45, null=True)),
                ('nit', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id_tax', models.AutoField(primary_key=True, serialize=False)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax_name', models.CharField(max_length=70)),
                ('creation_date', models.DateField()),
            ],
            options={
                'db_table': 'tax',
            },
        ),
        migrations.CreateModel(
            name='TaxPriceProduct',
            fields=[
                ('id_tax_price_product', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_price_product', models.ForeignKey(db_column='fk_id_price_product', on_delete=django.db.models.deletion.CASCADE, to='Sales.priceproduct')),
                ('fk_id_tax', models.ForeignKey(db_column='fk_id_tax', on_delete=django.db.models.deletion.CASCADE, to='Sales.tax')),
            ],
            options={
                'db_table': 'tax_price_product',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id_ticket', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_date', models.DateField()),
                ('half_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fk_id_person_cashier', models.ForeignKey(db_column='fk_id_person_cashier', on_delete=django.db.models.deletion.CASCADE, to='Sales.person')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='TicketDetail',
            fields=[
                ('id_ticket_detail', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('devolution_request', models.DateField(blank=True, null=True)),
                ('devolution_approved', models.DateField(blank=True, null=True)),
                ('description_devolution', models.CharField(blank=True, max_length=70, null=True)),
                ('fk_id_person_administrator', models.ForeignKey(blank=True, db_column='fk_id_person_administrator', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.person')),
                ('fk_id_tax_price_product', models.ForeignKey(db_column='fk_id_tax_price_product', on_delete=django.db.models.deletion.CASCADE, to='Sales.taxpriceproduct')),
                ('fk_id_ticket', models.ForeignKey(db_column='fk_id_ticket', on_delete=django.db.models.deletion.CASCADE, to='Sales.ticket')),
            ],
            options={
                'db_table': 'ticket_detail',
            },
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id_product_provider', models.AutoField(primary_key=True, serialize=False)),
                ('stock', models.IntegerField()),
                ('bar_code', models.CharField(max_length=45)),
                ('fk_id_product', models.ForeignKey(db_column='fk_id_product', on_delete=django.db.models.deletion.CASCADE, to='Sales.product')),
                ('fk_id_provider', models.ForeignKey(db_column='fk_id_provider', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.provider')),
            ],
            options={
                'db_table': 'product_provider',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fk_id_product_type',
            field=models.ForeignKey(db_column='fk_id_product_type', on_delete=django.db.models.deletion.CASCADE, to='Sales.producttype'),
        ),
        migrations.AddField(
            model_name='priceproduct',
            name='fk_id_product_provider',
            field=models.ForeignKey(db_column='fk_id_product_provider', on_delete=django.db.models.deletion.CASCADE, to='Sales.productprovider'),
        ),
        migrations.CreateModel(
            name='PersonPersonType',
            fields=[
                ('id_person_person_type', models.AutoField(primary_key=True, serialize=False)),
                ('fk_id_person', models.ForeignKey(db_column='fk_id_person', on_delete=django.db.models.deletion.CASCADE, to='Sales.person')),
                ('fk_id_person_type', models.ForeignKey(db_column='fk_id_person_type', on_delete=django.db.models.deletion.CASCADE, to='Sales.persontype')),
            ],
            options={
                'db_table': 'person_person_type',
            },
        ),
    ]
