# Generated by Django 3.2.9 on 2021-11-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_auto_20211103_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='fk_id_person_cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_person_cashier', to='Sales.person'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='fk_id_person_customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_id_person_customer', to='Sales.person'),
        ),
    ]
